# Site settings
title: Der Zürcher Iihschenker
#email:
description: >- 
  IaaS: Iihschenken as a Service: 
  Buchen sie mich für ihr Event und ihr Getränk. 

# Build settings
markdown: kramdown

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
