# Site settings
title: Der Iihschenker
#email:
description: >- 
  Iihschenken as a service

# Build settings
markdown: kramdown

remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
